Repository AgoraIO/Agora-WordPress, pull requests merged in 2020-03, with the labels that each got.

#33 Hotfix 20190305
  README.md
  public/class-wp-agora-page-template.php
  public/js/agora-broadcast-client.js
  public/js/agora-communication-client.js
  public/js/broadcast-ui.js
  public/js/communication-ui.js
  public/js/screen-share.js
  public/js/wp-agora-io-public.js
  public/views/agora-fullscreen-broadcast.php
  public/views/agora-fullscreen-template.php
  public/views/wp-agora-io-audience.php
  public/views/wp-agora-io-broadcast.php
  public/views/wp-agora-io-communication.php
  readme.txt
  wp-agora-io.php
Labels: bug

#34 Updated readme
  README.md
  readme.txt
Labels: documentation, enhancement

#35 Hotfix20190309
  README.md
  public/js/agora-broadcast-client.js
  public/js/agora-communication-client.js
  public/js/communication-ui.js
  public/views/agora-fullscreen-broadcast.php
  public/views/agora-fullscreen-template.php
  public/views/wp-agora-io-broadcast.php
  public/views/wp-agora-io-communication.php
  readme.txt
  wp-agora-io.php
Labels: bug

#36 Fix audience uid
  public/views/wp-agora-io-audience.php
  public/views/wp-agora-io-broadcast.php
Labels: bug

#37 release v1.3
  README.md
  readme.txt
  wp-agora-io.php
Labels: deployment prep

#38 updated readme: change log updates
  README.md
  readme.txt
Labels: deployment prep, documentation

#39 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#41 Updated SDK and bug fixes
  README.md
  admin/js/wp-agora-io-admin.js
  admin/views/agora-admin-settings.php
  public/class-wp-agora-io-public.php
  public/class-wp-agora-page-template.php
  public/js/agora/AgoraRTCSDK-2.9.0.js
  public/js/agora/AgoraRTCSDK-3.0.2.121.js
  public/views/agora-fullscreen-broadcast.php
  public/views/agora-fullscreen-template.php
  public/views/wp-agora-io-audience.php
  public/views/wp-agora-io-broadcast.php
  public/views/wp-agora-io-communication.php
  readme.txt
  wp-agora-io.php
Labels: bug, documentation, enhancement
